version: "3.9"

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - test

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - redis
    environment:
      - HOST=0.0.0.0
      - PORT=8010
      - REDIS_ADDRESS=redis:6379
    networks:
      - test

networks:
  test:
    name: test